language: go

go:
  - "1.x"

env:
  - GO111MODULE=on

before_install:
  - go mod download

script:
  - go build -v -ldflags="-s -w"
  - file ./bifrost
  - rm -rf ./bifrost

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true